services:
  sunrise:
    build: . # build the image from the local Dockerfile
    container_name: sunrise
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4173
    ports:
      - '127.0.0.1:4173:4173'
